### ISSUE TITLE
Does Block Cursor have to exist only for Vintage Mode?

### ISSUE THREAD

**Issue by dynajoe** [netpro2k/SublimeBlockCursor#10]
It'd be nice to use this package even if vintage mode is ignored.

**Comment by zjr** [comment]
+1

**Comment by sardaukar** [comment]
+1

**Comment by netpro2k** [comment]
This should now remain on when in command mode in vintage mode OR always if vinage mode is disabled

**Comment by dynajoe** [comment]
YAY!
