### ISSUE TITLE
Sublime Package Control installs old version

### ISSUE THREAD

**Issue by pkappler** [netpro2k/SublimeBlockCursor#11]
I just installed this plugin using Sublime Package Control and it doesn't contain the commit from Nov 23 https://github.com/netpro2k/SublimeBlockCursor/commit/f8a63c5b33fb7cce7c55068a7f644056f1a80edc. I'm not sure how quickly changes are supposed to be picked up, but surely it shouldn't take 15 days?

**Comment by netpro2k** [comment]
Ah good catch. It seems I have Package Control pulling from https://github.com/SublimeText/SublimeBlockCursor had to merge this change into that. Not too sure when Package Control checks for updates, but I think it should update now.
