### ISSUE TITLE
Block cursor does not disappear when first entering insert mode

### ISSUE THREAD

**Issue by eproxus** [netpro2k/SublimeBlockCursor#16]
The block doesn't disappear until the cursor is moved in insert mode, using Sublime Text build 3010 and SublimeBlockCursor commit 76c902d2ac.

**Comment by netpro2k** [comment]
Are you still seeing this? I am unable to reproduce. My cursor goes to standard pipe as soon as I enter insert mode.

**Comment by eproxus** [comment]
I actually stopped using Sublime Text 3 and went back to 2 for the time being, so I can't confirm. Sorry.

**Comment by netpro2k** [comment]
ah didnt even realize this was for ST3 ... Not going to worry about that yet heh
