### ISSUE TITLE
Any way to get rid of the outline?

### ISSUE THREAD

**Issue by jsahlen** [netpro2k/SublimeBlockCursor#18]
I'm getting an outline on the block, no matter which color scheme I'm using. Is there a way to get rid of it (by editing the color scheme or something else)?

![Screen Shot 2013-03-24 at 2 09 37 PM](https://f.cloud.github.com/assets/8138/295357/5bb192fe-9484-11e2-95a7-765b17598857.png)

**Comment by ingshtrom** [comment]
I think the best you can do is to set the outline color to be the same as the background color.  That is what I usually do, but there might be a better way.

**Comment by jsahlen** [comment]
That would be more than enough. What would be the syntax in the color scheme file to do so? I'm just now contemplating switching from Vim, so there's a lot of new stuff I haven't learned yet.

**Comment by ingshtrom** [comment]
I thought I had fixed that, but apparently I hadn't (I don't use Sublime Text for all of my coding).  I read that as of right now, due to limitations in the API and the way ST2 get's colors, that it isn't possible.  I tried for several hours yesterday to fix this.  Sorry about that.

**Comment by jsahlen** [comment]
No worries – thanks a lot for looking into it! Hopefully the API will be
expanded or they will add a real block cursor at some point.

On Tuesday, March 26, 2013, Alex Hokanson wrote:

> I thought I had fixed that, but apparently I hadn't (I don't use Sublime
> Text for all of my coding). I read that as of right now, due to limitations
> in the API and the way ST2 get's colors, that it isn't possible. I tried
> for several hours yesterday to fix this. Sorry about that.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/netpro2k/SublimeBlockCursor/issues/18#issuecomment-15435693
> .

## 

---

Johan Sahlén / Monospace
+46 (0)70 698 38 27
http://monospace.se

**Comment by netpro2k** [comment]
Like ingshtrom said, this does not seem to be possible with ST2's current API
