### ISSUE TITLE
README issue

### ISSUE THREAD

**Issue by liamcain** [netpro2k/SublimeBlockCursor#2]
The readme says that you can install Sublime Tweet through Package Control.  That may be true, but doesn't involve SublimeBlockCursor.  Probably just a copy-n-paste faux pas.

**Comment by mrmartineau** [comment]
I can confirm that this is still the case.

**Comment by jtmkrueger** [comment]
I can also confirm.

**Comment by netpro2k** [comment]
this was fixed awhile back
