### ISSUE TITLE
SublimeBlockCursor does not exist in Package Control

### ISSUE THREAD

**Issue by krzkrzkrz** [netpro2k/SublimeBlockCursor#3]
Reading the following:

"If you have the Package Control installed, you can install Sublime Tweet from inside Sublime Text itself. Open the Command Palette and select "Package Control: Install Package", then search for SublimeBlockCursor and you’re done!"

`SublimeBlockCursor` doesn't exist in `Package Controler: Install Package`. I see other packages, but not `SublimeBlockCursor`.

Anyone know why?

**Comment by dimensia** [comment]
The documentation is incomplete.

Use "Package Control:  Add Repository" and then paste in the URL for this repository:

https://github.com/netpro2k/SublimeBlockCursor

You should then be able to use "Package Control:  Install Package" to install the package.

**Comment by netpro2k** [comment]
It should now be in the main package control repository, no need to add it manually
