### ISSUE TITLE
can't get it installed in theme

### ISSUE THREAD

**Issue by tobsn** [netpro2k/SublimeBlockCursor#6]
i tried adding the dict in various positions but i can't get it working - is there a specific place in the xml it has to be put? right now it either throws an error that there is something wrong with the xml or the block cursor does not shot up.

**Comment by netpro2k** [comment]
It should be in the "Settings" array, like so:

``` xml
<key>settings</key>
<array>
    <dict>
        <key>name</key>
        <string>Block Cursor</string>
        <key>scope</key>
        <string>block_cursor</string>
        <key>settings</key>
        <dict>
            <key>foreground</key>
            <string>#212121</string>
            <key>background</key>
            <string>#9ca9b7</string>
        </dict>
    </dict>
    <!-- other stuff -->
</array>
```

**Comment by tobsn** [comment]
doesnt work :/

**Comment by netpro2k** [comment]
Nope, i added it in my color_scheme file "twilight.tmTheme" ( https://gist.github.com/5363d381fdf29328bda5 ). This is saved in my User directory and then referenced in my user preferences file like so `"color_scheme": "Packages/User/Twilight.tmTheme"`

**Comment by wpowers** [comment]
Same issue - added it in the Nil theme at Tubnil Bright.tmTheme and no love.
