### ISSUE TITLE
Block doesn't change when leaving command mode

### ISSUE THREAD

**Issue by fedesilvaponte** [netpro2k/SublimeBlockCursor#7]
When you are in command mode and press "a", for example, the block stays in command mode until another key is pressed. This turns out to be very confusing.

**Comment by netpro2k** [comment]
cant reproduce this. Still an issue?

**Comment by ccschmitz** [comment]
I just installed this today and am having the same issue. When you enter insert mode the cursor stays as a block until you insert a character.

**Comment by ccschmitz** [comment]
Just installed this again today and everything is working as I would expect it to.
