### ISSUE TITLE
Block Cursor Border

### ISSUE THREAD

**Issue by hspak** [netpro2k/SublimeBlockCursor#9]
Is there a way to change the border of the block? It is an annoying bright green/teal color. Changing the foreground/background colors do not affect it. I am using the Dev Build on Linux.

**Comment by robnyman** [comment]
Same question here.

**Comment by netpro2k** [comment]
Dug through the sublimetext docs and as far as I can tell the outline of a "region" cant be changed when that region is being filled in. When a region is set to only outline, `background` is used to set its outline color. Fwiw, this color changes depending on the color of your background and cursor background...
